name: Build Armbian's Kernel for Arch-based

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "manjaro" ]
  pull_request:
    branches: [ "manjaro" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Arch Linux x86_64 Chroot
      run: |
        sudo apt update && sudo apt install arch-install-scripts
        wget https://geo.mirror.pkgbuild.com/iso/latest/archlinux-bootstrap-x86_64.tar.zst -q
        sudo tar xf archlinux-bootstrap-x86_64.tar.zst
        rm archlinux-bootstrap-x86_64.tar.zst pkglist.x86_64.txt
        sudo sed -i 's|CheckSpace|#CheckSpace|g' root.x86_64/etc/pacman.conf
        sudo arch-chroot root.x86_64 pacman-key --init
        sudo arch-chroot root.x86_64 pacman-key --populate
        sudo sed -i 's|#Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch|Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch|g' root.x86_64/etc/pacman.d/mirrorlist
        sudo arch-chroot root.x86_64 pacman -Syu --noconfirm --needed --disable-download-timeout base-devel sudo git
        sudo sed -i 's|#MAKEFLAGS="-j2"|MAKEFLAGS="-j$(nproc --all)"|g' root.x86_64/etc/makepkg.conf
        sudo sed -i 's|# %wheel ALL=(ALL:ALL) NOPASSWD: ALL|%wheel ALL=(ALL:ALL) NOPASSWD: ALL|g' root.x86_64/etc/sudoers
        sudo arch-chroot root.x86_64 useradd -m -s /bin/bash builder
        sudo arch-chroot root.x86_64 usermod -g wheel builder
    - name: Build
      run: |
        sudo arch-chroot root.x86_64 su builder -c 'git clone https://github.com/qqdasb/linux-aarch64-rockchip-6.1-armbian-git-cross /home/builder/linux-aarch64-rockchip-6.1-armbian-git-cross'
        sudo arch-chroot root.x86_64 su builder -c 'cd /home/builder/linux-aarch64-rockchip-6.1-armbian-git-cross && makepkg -s -A --noconfirm'
        sudo mv root.x86_64/home/builder/linux-aarch64-rockchip-6.1-armbian-git-cross/linux-aarch64-rockchip-6.1-armbian-git-rkr4.1-1-aarch64.pkg.tar.zst .
        sudo mv root.x86_64/home/builder/linux-aarch64-rockchip-6.1-armbian-git-cross/linux-aarch64-rockchip-6.1-armbian-git-headers-rkr4.1-1-aarch64.pkg.tar.zst .
    - name: 'Upload Built Packages'
      uses: actions/upload-artifact@v4
      with:
        name: Arch-based-kernel-armbian
        path: ./*.zst
