name: Build Armbian's Kernel for Arch-based

on:
#  schedule:
#    - cron: "0 0 * * *"
  push:
    branches: [ "manjaro" ]
  pull_request:
    branches: [ "manjaro" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Arch Linux ARM Chroot
      run: |
        sudo apt update && sudo apt install arch-install-scripts qemu-user-static
        sudo systemctl restart systemd-binfmt
        wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz -q
        mkdir rootfs
        sudo tar xf ArchLinuxARM-aarch64-latest.tar.gz -C rootfs
        rm ArchLinuxARM-aarch64-latest.tar.gz
        sudo cp /usr/bin/qemu-aarch64-static rootfs/usr/bin/
        sudo sed -i 's|CheckSpace|#CheckSpace|g' rootfs/etc/pacman.conf
        sudo arch-chroot rootfs pacman-key --init
        sudo arch-chroot rootfs pacman-key --populate
        sudo arch-chroot rootfs pacman -R --noconfirm linux-aarch64 linux-firmware
        sudo arch-chroot rootfs pacman -Syu --noconfirm --needed base-devel sudo git cpio xmlto docbook-xsl inetutils bc dtc
        sudo sed -i 's|# $wheel  ALL=(ALL:ALL) NOPASSWD:ALL|$wheel  ALL=(ALL:ALL) NOPASSWD:ALL|g' rootfs/etc/sudoers
        sudo arch-chroot rootfs useradd -m -s /bin/bash builder
        sudo arch-chroot rootfs usermod -g wheel builder
    - name: Build
      run: |
        sudo arch-chroot rootfs su builder -c 'git clone https://github.com/qqdasb/linux-aarch64-rockchip-rk6.1-opi3b-git /home/builder/linux-aarch64-rockchip-rk6.1-opi3b-git'
        sudo arch-chroot rootfs su builder -c 'cd /home/builder/linux-aarch64-rockchip-rk6.1-opi3b-git && makepkg -s'
        sudo mv rootfs/home/builder/linux-aarch64-rockchip-rk6.1-opi3b-git/*.zst .
    - name: 'Upload Built Packages'
      uses: actions/upload-artifact@v4
      with:
        name: Arch-based-kernel-armbian
        path: ./*.zst
