name: Build Armbian (Sid)

on:
#  schedule:
#    - cron: "0 0 * * *"
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh BOARD=orangepi3b BRANCH=edge NETWORKING_STACK=network-manager RELEASE=sid ENABLE_EXTENSIONS=v4l2loopback-dkms,mesa-vpu,u-boot-menu,rkbin-tools,preset-firstrun KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=no EXTERNAL=yes INSTALL_HEADERS=yes
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-sid-edge-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-packages
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/debs/*
