name: Build Armbian Minimal (Noble)

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        sudo insmod /lib/modules/6.5.0-1025-azure/kernel/lib/raid6/raid6_pq.ko
        sudo insmod /lib/modules/6.5.0-1025-azure/kernel/crypto/xor.ko
        sudo insmod /lib/modules/6.5.0-1025-azure/kernel/lib/libcrc32c.ko
        sudo insmod /lib/modules/6.5.0-1025-azure/kernel/fs/btrfs/btrfs.ko
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh BOARD=orangepi3b BRANCH=vendor NETWORKING_STACK=network-manager BETA=yes RELEASE=noble EXPERT=yes KERNEL_CONFIGURE=no BUILD_MINIMAL=yes ROOTFS_TYPE=btrfs BTRFS_COMPRESSION=zstd ENABLE_EXTENSIONS=u-boot-menu
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-noble-vendor-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
