name: Build Armbian

on:
#  schedule:
#    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh DESKTOP_ENVIRONMENT=kde-plasma NETWORKING_STACK=network-manager RELEASE=noble BETA=yes ENABLE_EXTENSIONS=v4l2loopback-dkms,mesa-vpu DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base DESKTOP_APPGROUPS_SELECTED=browsers,chat,desktop_tools,editors,email,internet,languages,multimedia,office,programming,remote_desktop DESKTOP_ENVIRONMENT=gnome KERNEL_CONFIGURE=no BUILD_DESKTOP=no BUILD_MINIMAL=no EXTERNAL=yes INSTALL_HEADERS=yes EXTERNAL_NEW=compile BUILD_ALL=yes BOARD=orangepi3b BRANCH=vendor
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-noble-edge-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
