name: Build Fixed U-Boot Packages for Armbian

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        rm config/boards/orangepi3b.csc
        wget https://github.com/amazingfate/build/raw/76122197b554fa9c62b74cf4b11a0d7371942355/config/boards/orangepi3b.csc -O config/boards/orangepi3b.csc
        mkdir -p patch/u-boot/v2024.10-orangepi3b
        wget https://github.com/amazingfate/build/raw/76122197b554fa9c62b74cf4b11a0d7371942355/patch/u-boot/v2024.10-orangepi3b/0001-rockchip-rk3566-orangepi-3b-enable-npu-regulator.patch -O patch/u-boot/v2024.10-orangepi3b/0001-rockchip-rk3566-orangepi-3b-enable-npu-regulator.patch
        ./compile.sh uboot BOARD=orangepi3b KERNEL_CONFIGURE=no BRANCH=vendor
    - name: 'Upload deb'
      uses: actions/upload-artifact@v4
      with:
        name: Armbian-U-Boot-Fixes
        path: build/output/debs/*
