name: Build Armbian Noble (Btrfs)

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "armbian" ]
  pull_request:
    branches: [ "armbian" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Upgrade rsync
      run: |
        sudo apt update
        wget https://launchpadlibrarian.net/770856828/rsync_3.2.7-1ubuntu1.2_amd64.deb
        sudo apt install ./*.deb
    - name: Install Depends
      run: |
        sudo insmod /lib/modules/6.8.0-1017-azure/kernel/lib/raid6/raid6_pq.ko.zst
        sudo insmod /lib/modules/6.8.0-1017-azure/kernel/crypto/xor.ko.zst
        sudo insmod /lib/modules/6.8.0-1017-azure/kernel/fs/btrfs/btrfs.ko.zst
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh BOARD=orangepi3b BRANCH=vendor NETWORKING_STACK=network-manager BETA=yes RELEASE=noble EXPERT=yes KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=yes DESKTOP_ENVIRONMENT=gnome DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base DESKTOP_APPGROUPS_SELECTED=browsers,chat,desktop_tools,editors,email,internet,multimedia,office,programming,remote_desktop ENABLE_EXTENSIONS=u-boot-menu,mesa-vpu,v4l2loopback-dkms INSTALL_HEADERS=yes CONSOLE_AUTOLOGIN=yes ROOTFS_TYPE=btrfs BTRFS_COMPRESSION=zstd
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-noble-vendor-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
