name: Build U-Boot

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        git clone --depth 1 https://github.com/rockchip-linux/rkbin
        git clone --depth 1 https://source.denx.de/u-boot/u-boot.git
        sudo apt update && sudo apt install build-essential binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev flex gcc-multilib p7zip p7zip-full libglib2.0-dev qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync python3-pyelftools libpython3-dev python3-setuptools
    - name: Build
      run: |
        cd u-boot
        export ROCKCHIP_TPL=../rkbin/bin/rk35/rk3568_bl31_v1.34.elf
        export BL31=../rkbin/bin/rk35/rk3566_ddr_1056MHz_v1.21.bin
        make orangepi-3b-rk3566_defconfig
        make CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)
    - name: 'Upload Built Binary.'
      uses: actions/upload-artifact@v4
      with:
        name: u-boot
        path: u-boot/u-boot-rockchip.bin
