name: Build Armbian (Sid)

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        rm config/boards/orangepi3b.csc
        wget https://github.com/amazingfate/build/raw/76122197b554fa9c62b74cf4b11a0d7371942355/config/boards/orangepi3b.csc -O config/boards/orangepi3b.csc
        mkdir -p patch/u-boot/v2024.10-orangepi3b
        wget https://github.com/amazingfate/build/raw/76122197b554fa9c62b74cf4b11a0d7371942355/patch/u-boot/v2024.10-orangepi3b/0001-rockchip-rk3566-orangepi-3b-enable-npu-regulator.patch -O patch/u-boot/v2024.10-orangepi3b/0001-rockchip-rk3566-orangepi-3b-enable-npu-regulator.patch
        ./compile.sh BOARD=orangepi3b BRANCH=vendor NETWORKING_STACK=network-manager BETA=yes SHOW_DEBIAN=yes DESKTOP_APPGROUPS_SELECTED=browsers,desktop_tools,email,internet,languages,multimedia,remote_desktop DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base DESKTOP_ENVIRONMENT=kde-plasma RELEASE=sid ENABLE_EXTENSIONS=v4l2loopback-dkms,mesa-vpu,rkbin-tools EXPERT=yes BUILD_KSRC=yes INSTALL_KSRC=yes KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=yes EXTERNAL=yes INSTALL_HEADERS=yes
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-sid-vendor-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-packages
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/debs/*
