name: Build Armbian Kernel

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian Kernel
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        wget https://raw.githubusercontent.com/qqdasb/my-files/main/linux-5.10-rkr6.config
        wget https://raw.githubusercontent.com/qqdasb/my-files/main/linux-6.1-rkr1.config
        mkdir -p userpatches
        mv linux-5.10-rkr6.config userpatches/linux-rk35xx-legacy.config
        mv linux-6.1-rkr1.config userpatches/linux-rk35xx-vendor.config
        ./compile.sh kernel BOARD=orangepi3b BRANCH=vendor
        ./compile.sh kernel BOARD=orangepi3b BRANCH=legacy
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-Kernel-legacy-and-vendor
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/debs/*
