name: Build Armbian

on:
#  schedule:
#    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh NETWORKING_STACK=network-manager RELEASE=sid KERNEL_CONFIGURE=no BUILD_DESKTOP=no BUILD_MINIMAL=no EXTERNAL=yes INSTALL_HEADERS=yes EXTERNAL_NEW=compile BUILD_ALL=yes BOARD=orangepi3b BRANCH=edge
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-sid-edge-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
