name: Build Armbian (Noble)

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Armbian
      run: |
        git clone https://github.com/armbian/build --depth 1 -b main
        cd build
        ./compile.sh BOARD=orangepi3b BRANCH=vendor NETWORKING_STACK=network-manager BETA=yes RELEASE=noble ENABLE_EXTENSIONS=v4l2loopback-dkms,mesa-vpu,rkbin-tools EXPERT=yes KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=no EXTERNAL=yes INSTALL_HEADERS=yes
    - uses: actions/upload-artifact@v4
      with:
        name: Armbian-noble-vendor-opi3b
        path: /home/runner/work/build-opi3b/build-opi3b/build/output/images/*
