name: Build Armbian (Bookworm)

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: armbian/build@v24.2.1
        with:
          armbian_token:              "${{secrets.GITHUB_TOKEN}}"
          armbian_target:             build
          armbian_release:            sid
          armbian_kernel_branch:      vendor
          armbian_ui:                 minimal
          armbian_board:              orangepi3b
          armbian_release_tittle:     "Armbian Sid for Orange Pi 3B"
          armbian_release_body:       "Debian Sid for Orange Pi 3B"
          armbian_pgp_key:            "${{secrets.GPG_KEY1}}"
          armbian_pgp_password:       "${{secrets.GPG_PASSPHRASE1}}"
