name: Build Chromium with Electron and Rockchip MPP Patches

on:
  push:
    branches: [ "chromium-electron" ]
  pull_request:
    branches: [ "chromium-electron" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Fetch Source
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH=$PATH:$(pwd)/depot_tools
        mkdir ~/chromium && cd ~/chromium
        fetch --nohooks --no-history chromium
        cd src
        git fetch origin --tagsgit reset --hard 131.0.6778.268
        gclient sync --force --nohooks --with_branch_heads
    - name: Install Dependencies
      run: |
        cd src
        ./build/install-build-deps.sh
        gclient runhooks
    - name: Patch
      run: |
        cd src
        git apply -v ../*.patch
    - name: Build
      run: |
        cd src
        gn gen out/Release-Electron --args='is_debug = false symbol_level = 0 target_cpu = "arm64"'
    - uses: actions/upload-artifact@v4
      with:
        name: Chromium-with-Electron-MPP
        path: /home/runner/work/build-opi3b/build-opi3b/src/out/Release-Elecrton
