name: Build Electron with Rockchip MPP Patches

on:
  push:
    branches: [ "electron" ]
  pull_request:
    branches: [ "electron" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/setup-node@v4
      with:
        node-version: 22.13.0
    - name: Install depends
      run: |
        sudo apt-get update
        sudo apt-get install build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev curl gperf bison python3-dbusmock openjdk-8-jre libc6-dev-arm64-cross linux-libc-dev-arm64-cross g++-14-aarch64-linux-gnu ninja-build generate-ninja
    - name: Init Source
      run: |
        mkdir src
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH=$PATH:$(pwd)/depot_tools
        export CHROMIUM_BUILDTOOLS_PATH=$(pwd)/src/src/buildtools
        cd src
        gclient config --name "src/electron" --unmanaged https://github.com/qqdasb/electron-rkmpp
        gclient sync --with_branch_heads --with_tags --no-history
        cat src/build/args/release.gn
    - name: Install Depends from Electron
      run: |
        cd src/src
        cat build/install-build-deps.sh
        ./build/install-build-deps.sh --no-android
        ./build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
    - name: Build
      run: |
        cd src/src
        mkdir -p out/Release-arm64
        gn gen out/Release-arm64 --args='import("//electron/build/args/release.gn") target_cpu = "arm64"'
        ninja -C out/Release-arm64 electron -j$(nproc -a)
    - name: Package
      run: |
        cd src/src
        script/strip-binaries.py -d out/Release-arm64
        ninja -C out/Release-arm64 electron:electron_dist_zip -j$(nproc -a)
        find . -name *.zip
    - uses: actions/upload-artifact@v4
      with:
        name: Electron-With-RKMPP
        path: /home/runner/work/build-opi3b/build-opi3b/src/src/out/Release-arm64
