name: Manjaro ARM Minimal Modified

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        wget https://github.com/manjaro-arm/opi-3b-images/releases/download/20240131/Manjaro-ARM-minimal-opi3b-20240131.img.xz -q
        sudo apt update && sudo apt install arch-install-scripts qemu-user-static qemu-system-arm qemu-efi binfmt-support
        xz -d Manjaro-ARM-minimal-opi3b-20240131.img.xz
        mkdir -p manjaro
        sudo losetup -P /dev/loop3 Manjaro-ARM-minimal-opi3b-20240131.img
        sudo mount /dev/loop3p2 ./manjaro
        sudo mount /dev/loop3p1 ./manjaro/boot
        sudo cp /usr/bin/qemu-aarch64-static ./manjaro/usr/bin
    - name: Moding
      run: |
        sudo arch-chroot ./manjaro pacman-key --init
        sudo arch-chroot ./manjaro pacman-key --populate
        sudo arch-chroot ./manjaro pacman -Sy --noconfirm
        sudo arch-chroot ./manjaro pacman -Scc --noconfirm
        git clone https://github.com/armbian/firmware.git
        git clone https://github.com/orangepi-xunlong/firmware.git opi-firmware
        rm firmware/README.md opi-firmware/README.md
        cp -r opi-firmware/* firmware/
        sudo cp -r firmware/* ./manjaro/usr/lib/firmware/
        rm -rf firmware opi-firmware
        sudo arch-chroot ./manjaro mkdir ow-dir
        sudo arch-chroot ./manjaro pacman -S --needed lz4 xz zstd base lzo networkmanager iproute2 filesystem glibc dbus-broker systemd perl wpa_supplicant --noconfirm --overwrite ow-dir/*
        sudo arch-chroot ./manjaro systemctl enable NetworkManager
        sudo arch-chroot ./manjaro pacman -Scc --noconfirm
        sudo arch-chroot ./manjaro pacman-key --recv-keys BA27F219383BB875
        sudo arch-chroot ./manjaro pacman-key --lsign BA27F219383BB875
        sudo echo '[7Ji]
        Server = https://github.com/7Ji/archrepo/releases/download/$arch' | sudo tee -a ./manjaro/etc/pacman.conf
        sudo arch-chroot ./manjaro pacman -Sy 7ji-keyring --needed --noconfirm
        sudo arch-chroot ./manjaro pacman -Rdd linux-rc linux-rc-headers --noconfirm
        sudo arch-chroot ./manjaro pacman -S mkinitcpio --needed --noconfirm --overwrite ow-dir/*
        sudo arch-chroot ./manjaro pacman -S linux-aarch64-rockchip-opi3b-npu-w568w --noconfirm
        sudo arch-chroot rm -rf ow-dir
        sudo arch-chroot ./manjaro mkinitcpio -k /boot/vmlinuz-linux-aarch64-rockchip-opi3b-npu-w568w -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-aarch64-rockchip-opi3b-npu-w568w.img -v -z xz
        sudo arch-chroot ./manjaro ldconfig
        sudo arch-chroot ./manjaro sync
        sudo rm ./manjaro/usr/bin/qemu-aarch64-static
        sudo umount ./manjaro/boot
        sudo umount ./manjaro
        sudo losetup -d /dev/loop3
        mv ./Manjaro-ARM-minimal-opi3b-20240131.img ./Manjaro-ARM-Minimal-OPI3B-Modified.img
    - name: 'Upload Modified Image'
      uses: actions/upload-artifact@v4
      with:
        name: Manjaro-ARM-OPI3B-Modified
        path: ./Manjaro-ARM-Minimal-OPI3B-Modified.img
