name: Manjaro ARM Minimal Modified

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        wget https://github.com/manjaro-arm/opi-3b-images/releases/download/20240131/Manjaro-ARM-minimal-opi3b-20240131.img.xz -q
        sudo apt update && sudo apt install arch-install-scripts systemd-container qemu-user-static
        xz -d Manjaro-ARM-minimal-opi3b-20240131.img.xz
        mkdir -p manjaro
        sudo losetup -P /dev/loop3 ./Manjaro-ARM-minimal-opi3b-20240131.img
        sudo mount /dev/loop3p2 ./manjaro
    - name: Building
      run: |
        sudo arch-chroot ./manjaro pacman-key --init
        sudo arch-chroot ./manjaro pacman-key --populate
        sudo arch-chroot ./manjaro pacman -Sy --noconfirm
        sudo arch-chroot ./manjaro pacman -S --needed networkmanager --noconfirm
        git clone https://github.com/Joshua-Riek/ubuntu-rockchip-firmware.git
        rm -rf ubuntu-rockchip-firmware/debian README.md
        sudo cp ubuntu-rockchip-firmware manjaro/usr/lib/firmware
        git clone https://github.com/orangepi-xunlong/firmware.git
        sudo cp -r manjaro/usr/lib/firmware
        rm -rf ubuntu-rockchip-firmware firmware
        sudo arch-chroot ./manjaro ldconfig
        sudo arch-chroot ./manjaro sync
        sudo umount ./manjaro
        sudo e2fsck -fyD /dev/loop3p2
        sudo losetup -d /dev/loop3
        sudo resize2fs ./Manjaro-ARM-minimal-opi3b-20240131.img
