name: Manjaro ARM Minimal Modified

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: |
        wget https://github.com/manjaro-arm/opi-3b-images/releases/download/20240131/Manjaro-ARM-minimal-opi3b-20240131.img.xz -q
        sudo apt update && sudo apt install arch-install-scripts qemu-user-static qemu-system-arm qemu-efi binfmt-support
        xz -d Manjaro-ARM-minimal-opi3b-20240131.img.xz
        mkdir -p manjaro
        sudo losetup -P /dev/loop3 Manjaro-ARM-minimal-opi3b-20240131.img
        sudo mount /dev/loop3p2 ./manjaro
        sudo mount /dev/loop3p1 ./manjaro/boot
    - name: Moding
      run: |
        sudo arch-chroot ./manjaro pacman-key --init
        sudo arch-chroot ./manjaro pacman-key --populate
        sudo arch-chroot ./manjaro pacman -Sy --noconfirm
        git clone https://github.com/orangepi-xunlong/firmware.git
        git clone https://github.com/Joshua-Riek/ubuntu-rockchip-firmware.git
        rm -rf ubuntu-rockchip-firmware/debian firmware/README.md
        cp -r firmware/* ubuntu-rockchip-firmware/
        sudo cp ./ubuntu-rockchip-firmware ./manjaro/usr/lib/firmware
        rm -rf ubuntu-rockchip-firmware firmware
        sudo arch-chroot ./manjaro ldconfig
        sudo arch-chroot ./manjaro pacman -Scc --noconfirm
        sudo arch-chroot ./manjaro pacman -S --needed networkmanager glibc filesystem coreutils iproute2 systemd dbus --noconfirm --overwrite /usr/lib/systemd/system/dbus.service
        sudo arch-chroot ./manjaro systemctl enable NetworkManager
        sudo arch-chroot ./manjaro pacman -Scc --noconfirm
        sudo arch-chroot ./manjaro sync
        sudo umount ./manjaro/boot
        sudo umount ./manjaro
        sudo losetup -d /dev/loop3
        mv ./Manjaro-ARM-minimal-opi3b-20240131.img ./Manjaro-ARM-Minimal-OPI3B-Modified.img
    - name: 'Upload Modified Image'
      uses: actions/upload-artifact@v4
      with:
        name: Manjaro-ARM-OPI3B-Modified
        path: ./Manjaro-ARM-Minimal-OPI3B-Modified.img
