name: Manjaro ARM Minimal Modified

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Prepare
      run: |
        wget https://github.com/manjaro-arm/opi-3b-images/releases/download/20240131/Manjaro-ARM-minimal-opi3b-20240131.img.xz -q
        sudo apt update && sudo apt install arch-install-scripts qemu-user-static binfmt-support
        xz -d Manjaro-ARM-minimal-opi3b-20240131.img.xz
        sudo e2fsck -f Manjaro-ARM-minimal-opi3b-20240131.img
        sudo resize2fs Manjaro-ARM-minimal-opi3b-20240131.img
        mkdir -p manjaro
        sudo losetup -P /dev/loop3 ./Manjaro-ARM-minimal-opi3b-20240131.img
        sudo mount /dev/loop3p2 ./manjaro
        sudo mount /dev/loop3p1 ./manjaro/boot
    - name: Building
      run: |
        sudo cp /usr/bin/qemu-aarch64-static ./manjaro/usr/bin
        sudo arch-chroot ./manjaro pacman-key --init
        sudo arch-chroot ./manjaro pacman-key --populate
        git clone https://github.com/Joshua-Riek/ubuntu-rockchip-firmware.git
        rm -rf ubuntu-rockchip-firmware/debian README.md
        sudo cp -r ubuntu-rockchip-firmware manjaro/usr/lib/firmware
        git clone https://github.com/orangepi-xunlong/firmware.git
        sudo cp -r firmware manjaro/usr/lib/firmware
        rm -rf ubuntu-rockchip-firmware firmware
        sudo arch-chroot ./manjaro ldconfig
        sudo arch-chroot ./manjaro pacman -Syu --noconfirm
        sudo arch-chroot ./manjaro pacman -Scc --noconfirm
        sudo arch-chroot ./manjaro pacman -S --needed networkmanager --noconfirm
        sudo arch-chroot ./manjaro pacman -Scc --noconfirm
        sudo arch-chroot ./manjaro sync
        sudo rm ./manjaro/usr/bin/qemu-aarch64-static
        sudo umount ./manjaro/boot
        sudo umount ./manjaro
        sudo losetup -d /dev/loop3
        mv ./Manjaro-ARM-minimal-opi3b-20240131.img ./Manjaro-ARM-Minimal-OPI3B.img
    - name: 'Upload Modified Image'
      uses: actions/upload-artifact@v4
      with:
        name: Manjaro-ARM-Minimal-OPI3B-Modified
        path: ./Manjaro-ARM-Minimal-OPI3B.img
